### ISSUE TITLE
Working with databases

### ISSUE THREAD

**Issue by rooddood** [smoh/imageviewer#1]
I am trying to get this to work with a database. This app works with a CSV file, but I want to get the data directly from a database, do you have any insight on this?

**Comment by smoh** [comment]
No, not much -- it's something I'd have to learn myself, and I haven't had an immediate motivation for it. It also depends a lot on specifics; if it's just sqlite flat-file database, walking through [flask tutorial](http://flask.pocoo.org/docs/0.12/tutorial/) should be useful. If it's a more full-fledged database, I'd look into sqlalchemy and flask-sqlalchemy extension.
