### ISSUE TITLE
Traversing through example/images

### ISSUE THREAD

**Issue by sshah98** [smoh/imageviewer#2]
Hi, 

I am having an issue with the static folder. I want the directory to be as such: 
example
--> images
------------> 1
-------------------> image1.jpg
-------------------> image2.jpg
------------> 2
------------> 3

Therefore, how do I use the app.py and pager.py to traverse through the directory, such that I can receive image1.jpg on the index 1, and be able to view image2.jpg with a button on the same html page.

**Comment by smoh** [comment]
(Bear in mind that I'm not an expert web developer)
So as I understand, you want to 'toggle' another image (image2.jpg) on the same page, but paginate per directories (1, 2, 3) with two images. I'd just do it with javascript:
- load two images on the page (so there are two` <img src=...>`) but hide the second by default
- give the second image an `id` attribute, and add a button and make it hide/show this element using e.g., jquery [toggle](https://www.w3schools.com/jquery/jquery_hide_show.asp)

**Comment by sshah98** [comment]
Thank you. How would I be able to scale this such that it is not just two images, but thousands? I feel like using javascript for each `<img src=...>` might be counterintuitive, so what would be another solution?

**Comment by smoh** [comment]
You want to show thousands of images on one page? I'm not sure why you want to do that, but lazy-loading jQuery/javascript libraries are perhaps useful. I don't have much experience here.

(FYI, if what you want is to paginate images in each subdirectories (1, 2, 3 ..), modifying this template's paths/pager should suffice.)

**Comment by sshah98** [comment]
No, I want to display the most recent image as such:

![screenshot](https://user-images.githubusercontent.com/28765290/37936187-91623ada-3122-11e8-920c-dcf0f47dea13.png)

The bottom bar is not necessary, but essentially, those are all the images within that specific directory. 

Thank you, I will try and modify the template you provided.
